
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aula_07-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aula_07-service
  template:
    metadata:
      labels:
        app: aula_07-service
    spec:
      containers:
        - name: aula_07-service
          image: aula_07-service-image
          ports:
            - containerPort: 8080
